name: Gradle Build and Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3 : Exécuter les tests avec JaCoCo
      - name: Run Tests with JaCoCo
        run: ./gradlew test jacocoTestReport

      # Étape 4 : Publier les résultats des tests
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/**/*.xml

      # Étape 5 : Publier le rapport de couverture JaCoCo (HTML et XML)
      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-report
          path: build/reports/jacoco/test/html
